In [9]:
import numpy as np
from numpy import genfromtxt
data = genfromtxt('../DATA/bank_note_data.txt', delimiter=',')

In [10]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [11]:
len(data)

1372

In [12]:
labels = data[:,4]

In [13]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [14]:
features = data[:,0:4]

In [15]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [16]:
X = features
y = labels

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [26]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.5127  ,  2.9073  ,  1.0579  ,  0.40774 ],
       [ 5.504   , 10.3671  , -4.413   , -4.0211  ],
       [-0.2062  ,  9.2207  , -3.7044  , -6.8103  ]])

In [41]:
len(X_train)

919

In [28]:
from sklearn.preprocessing import MinMaxScaler

In [30]:
scaler_object = MinMaxScaler()

In [31]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [32]:
scaled_X_train = scaler_object.transform(X_train)

In [35]:
scaled_X_train.max()

1.0000000000000002

In [37]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [38]:
# Creates model
model = Sequential()
# 8 Neurons, expects input of 4 features. 
# Play around with the number of neurons!!
model.add(Dense(4, input_dim=4, activation='relu'))
# Add another Densely Connected layer (every neuron connected to every neuron in the next layer)
model.add(Dense(8, activation='relu'))
# Last layer simple sigmoid function to output 0 or 1 (our label)
model.add(Dense(1, activation='sigmoid'))

In [39]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9         
Total params: 69
Trainable params: 69
Non-trainable params: 0
_________________________________________________________________


In [40]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [42]:
# Play around with number of epochs as well!
model.fit(scaled_X_train,y_train,epochs=50, verbose=2)

Epoch 1/50
 - 2s - loss: 0.6837 - acc: 0.5734
Epoch 2/50
 - 0s - loss: 0.6771 - acc: 0.6507
Epoch 3/50
 - 0s - loss: 0.6710 - acc: 0.6866
Epoch 4/50
 - 0s - loss: 0.6654 - acc: 0.7203
Epoch 5/50
 - 0s - loss: 0.6599 - acc: 0.7258
Epoch 6/50
 - 0s - loss: 0.6539 - acc: 0.7334
Epoch 7/50
 - 0s - loss: 0.6461 - acc: 0.7497
Epoch 8/50
 - 0s - loss: 0.6385 - acc: 0.7486
Epoch 9/50
 - 0s - loss: 0.6298 - acc: 0.7584
Epoch 10/50
 - 0s - loss: 0.6188 - acc: 0.7497
Epoch 11/50
 - 0s - loss: 0.6092 - acc: 0.7715
Epoch 12/50
 - 0s - loss: 0.5996 - acc: 0.7758
Epoch 13/50
 - 0s - loss: 0.5898 - acc: 0.7835
Epoch 14/50
 - 0s - loss: 0.5801 - acc: 0.7911
Epoch 15/50
 - 0s - loss: 0.5702 - acc: 0.7933
Epoch 16/50
 - 0s - loss: 0.5606 - acc: 0.8009
Epoch 17/50
 - 0s - loss: 0.5510 - acc: 0.8020
Epoch 18/50
 - 0s - loss: 0.5411 - acc: 0.8074
Epoch 19/50
 - 0s - loss: 0.5316 - acc: 0.8052
Epoch 20/50
 - 0s - loss: 0.5227 - acc: 0.8172
Epoch 21/50
 - 0s - loss: 0.5133 - acc: 0.8150
Epoch 22/50
 - 0s - lo

In [43]:
scaled_X_test

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.76115065, 0.62415668, 0.27251204, 0.83616757],
       [0.9047516 , 0.90329171, 0.03658247, 0.42267079],
       [0.49296526, 0.86039507, 0.06714046, 0.1622583 ]])

In [44]:
model.predict(scaled_X_test)

array([[0.24407342],
       [0.45588124],
       [0.3266357 ],
       [0.25231376],
       [0.24407342],
       [0.24407342],
       [0.34742212],
       [0.24407342],
       [0.24407342],
       [0.29691458],
       [0.5221864 ],
       [0.8097313 ],
       [0.40040973],
       [0.84466857],
       [0.78194124],
       [0.29204336],
       [0.9044489 ],
       [0.90956366],
       [0.9329167 ],
       [0.8655896 ],
       [0.24407342],
       [0.24407342],
       [0.880725  ],
       [0.24407342],
       [0.97627276],
       [0.24407342],
       [0.24407342],
       [0.877376  ],
       [0.24407342],
       [0.24407342],
       [0.63592166],
       [0.25934273],
       [0.34671748],
       [0.9896836 ],
       [0.95588624],
       [0.24407342],
       [0.499778  ],
       [0.7680959 ],
       [0.8288194 ],
       [0.2455793 ],
       [0.24407342],
       [0.6322278 ],
       [0.75644135],
       [0.24407342],
       [0.96622276],
       [0.89251286],
       [0.929282  ],
       [0.244

In [45]:
scaled_X_test = scaler_object.transform(X_test)

In [46]:
scaled_X_test

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.76115065, 0.62415668, 0.27251204, 0.83616757],
       [0.9047516 , 0.90329171, 0.03658247, 0.42267079],
       [0.49296526, 0.86039507, 0.06714046, 0.1622583 ]])

In [47]:
model.predict(scaled_X_test)

array([[0.24407342],
       [0.45588124],
       [0.3266357 ],
       [0.25231376],
       [0.24407342],
       [0.24407342],
       [0.34742212],
       [0.24407342],
       [0.24407342],
       [0.29691458],
       [0.5221864 ],
       [0.8097313 ],
       [0.40040973],
       [0.84466857],
       [0.78194124],
       [0.29204336],
       [0.9044489 ],
       [0.90956366],
       [0.9329167 ],
       [0.8655896 ],
       [0.24407342],
       [0.24407342],
       [0.880725  ],
       [0.24407342],
       [0.97627276],
       [0.24407342],
       [0.24407342],
       [0.877376  ],
       [0.24407342],
       [0.24407342],
       [0.63592166],
       [0.25934273],
       [0.34671748],
       [0.9896836 ],
       [0.95588624],
       [0.24407342],
       [0.499778  ],
       [0.7680959 ],
       [0.8288194 ],
       [0.2455793 ],
       [0.24407342],
       [0.6322278 ],
       [0.75644135],
       [0.24407342],
       [0.96622276],
       [0.89251286],
       [0.929282  ],
       [0.244

In [48]:
model.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    

In [49]:
model.metrics_names

['loss', 'acc']

In [50]:
model.evaluate(x=scaled_X_test,y=y_test)

453/453 [==============================] - 0s 226us/step


[0.2960312753323688, 0.9271523178807947]

In [51]:
from sklearn.metrics import confusion_matrix,classification_report

In [52]:
predictions = model.predict_classes(scaled_X_test)

In [53]:
predictions


array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    

In [54]:
confusion_matrix(y_test,predictions)

array([[243,  14],
       [ 19, 177]], dtype=int64)

In [55]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.93      0.95      0.94       257
        1.0       0.93      0.90      0.91       196

avg / total       0.93      0.93      0.93       453

